### PR TITLE
Got rid of 1200 resharper warnings.

### PR DESCRIPTION
**Pull request by c-j-hughes**
These changes address a mixture of ReSharper noise, and minor improvements.

There are still a few errors in there. One is that AseDecimal constructors accept a precision argument, that is never used. Looking at this, the way AseDecimal is implemented is to use BigDecimal as a backing field which uses mantissa+exponent, whereas the AseDecimal has scale+precision. 

I assume that BigDecimal just changes size to accommodate whatever data is given to it - in which case the `precision` parameter isn't required. Not sure what that does from a compatibility perspective. What are your thoughts @senseibaka ?

### CODE REVIEW

**Comment by senseibaka** [comment]
Yeah, our `AseDecimal` implementation doesn't align with the constructor parameters. It might be good to see if `precision` can/should be used internally. So far it hasn't been needed 😜 

From a compatibility perspective, the reference driver's AseDecimal has the following constructor signatures, that should be maintained for drop-in purposes...
```
public AseDecimal() // by virtue of being a struct?
public AseDecimal(int precision, int scale)
public AseDecimal(AseDecimal inputDecimal)
public AseDecimal(int precision, int scale, byte[] value)
public AseDecimal(Decimal value)
```
There is also behavioural compatibility to consider. I think I did consider this a little, but the unit tests aren't run against the reference driver's implementation -- it might be good to do that

**Comment by c-j-hughes** [comment]
Ok. Will treat the AseDecimal investigation as a separate PR.

**Comment by senseibaka** [comment]
Hmm, I'm unable to run the Integration tests, they're all hanging.

**Comment by c-j-hughes** [comment]
They run for me... I had a hanging issue a while ago where the ASE went into log suspend when it ran out of TempDB space.

**Pull request merged**
