### PR TITLE
Fix for Unhandled TDS_ORDERBY

### PR DESCRIPTION
**Pull request by driseley**
Test and proposed fix for DataAction/AdoNetCore.AseClient#104

### CODE REVIEW

**Comment by senseibaka** [comment]
To properly handle `TDS_ORDERBY`, you should implement something like `OrderByToken : IToken` and register it in the `TokenParser`. Have a look at some of the existing token implementations to get an idea of what's needed.

Meanwhile I'm going to rectify the gaping issue with the catch-all token's length calculator... Your current change wouldn't be necessary if it worked correctly 😜

**Comment by driseley** [comment]
Thanks @senseibaka.  I did look at doing that but as I don't need the OrderBy information (and can't really see how to expose that info in the driver anyhow... ), I'm happy to withdraw this PR in favour of your fix for #107?

Would there be any chance of an early NuGet release for the fix for #107 - as we are having to use a custom build of the driver at the moment?

**Comment by senseibaka** [comment]
Yeah, I'm not sure how it'd be exposed by the driver either... It might tie in to some higher-level ORM thing.

In terms of getting an early release, I've actually just gone on holiday for a few weeks, but @c-j-hughes might be able to step in?

**Comment by driseley** [comment]
Withdrawing this in favour of #108

**Pull request closed without merging**
