### PR TITLE
Fixed so PoolSize cant be negative. "Fixes #158". Made sure pooling not …

### LINKED ISSUE #158: When DB is offline at app start, duplicate connections spawn after connection restored
**Describe the bug**
When using connection pooling and when the DB is offline when the first DB execution occurs,   `ConnectionPool.PoolSize` decrements (in `ConnectionPool.RemoveConnection`) to a negative number as it keeps failing (throwing exceptions) while creating connections in the `CheckAndIncrementPoolSize` loop. 

When the DB comes back online and connections begin to succeed, the `CheckAndIncrementPoolSize` loop keeps successfully adding new connections to the pool as it attempts to get the pool size to MinPoolSize. 

When `PoolSize` for example is at -20 when connections start to succeed, it will create 21 connections in the database (when `MinPoolSize` set to 1). Depending on how negative the number is, it has the potential to use up all the available connections for the server and lock it up.

**To Reproduce**
The easy way is to pretend db is offline by making your app offline so it can't connect to the DB.

1. Disconnect internet from the machine running your app.
2. Start your app and allow it run 
3. Attempt some kind of a query/execution against the DB
(It will fail of course but at this point `ConnectionPool` has been instantiated and its `TryFillPoolToMinSize` loop has been kicked off, and as it runs it will keep decrementing `PoolSize`)
4. Give it a few minutes and `PoolSize` will be somewhere around -10 and now connect the internet.
5. Inspect the DB and notice it starts creating duplicate connections

**Expected behavior**
`PoolSize` should never go below zero and thus there should never be extra connections that get created when connection is restored.

**Environment**
- .Net Core version 3.0
- `AdoNetCore.AseClient` nuget package version 0.16.0

**Additional context**
"Charset=iso_1;Min Pool Size=1;Max Pool Size=5;LoginTimeOut=5;ConnectionIdleTimeout=10; ConnectionLifetime=15;"

### PR DESCRIPTION
**Pull request by ts46235**
…kicked off if _parameters.Pooling==false

### CODE REVIEW

**Comment by senseibaka** [comment]
Interesting. Since `TryFillPoolToMinSize` increments `PoolSize`, it would be good to know where the race condition is that results in negative `PoolSize`...

This PR should prevent the value going negative, which is nice, but it would also be good to track down and solve the root cause... Do you have any thoughts?

**Comment by ts46235** [comment]
image

In our app we are running a health check every 30 seconds. When it tries to `GetNewConnection` it fails and catches the thrown exception and calls `RemoveConnection()`, which decrements `PoolSize`. This is outside of the loop that runs in `ConnectionPool` (which increments/decrements `PoolSize`) and in this flow there are no increments, just decrements so I assume that is the underlying issue.
```
try
            {
                Logger.Instance?.WriteLine($"{nameof(CreateNewPooledConnection)} start");
                return await _connectionFactory.GetNewConnection(cancellationToken, eventNotifier);
            }
            catch
            {
                Logger.Instance?.WriteLine($"{nameof(CreateNewPooledConnection)} failed");
                RemoveConnection();
                throw;
            }
```

**Comment by senseibaka** [comment]
Ah, I think I see!

It looks like there's a doubling-up of `RemoveConnection` calls, since `TryFillPoolToMinSize` (and `TryReplaceConnection`, too), and `CreateNewPooledConnection` are both calling it...

**Comment by ts46235** [comment]
Yes. You can update my PR or make a new one if you think you need to address that, but either way we are eager to get a new release integrated so our DBA stops being mad at us :)

**Comment by senseibaka** [comment]
@ts46235 Sorry, I'm unable to do a release at the moment, being the time of the year that it is. I'm hoping to do a release while I'm on holiday break.

In the meantime however, you do still have the option of using a build from your fixed branch

**Pull request merged**
